torchrun --nproc_per_node=1 main.py \
  --model convnext_tiny --drop_path 0.5 --input_size 384 \
  --batch_size 12 --lr 2e-4 --update_freq 2 --nb_classes 3 \
  --warmup_epochs 0 --epochs 60 --weight_decay 1e-8 \
  --head_init_scale 0.001 --cutmix 0 --mixup 0 \
  --save_ckpt_num 2 --dist_eval False \
  --color_jitter 0.2 \
  --finetune ckpt/checkpoint-13.pth \
  --data_path ./train/ \
  --eval_data_path ./train/ \
  --imset ./ \
  --data_set json \
  --output_dir ./output/
